// UFANVELI Shop and Warehouse Locations
export const LOCATIONS = {
  shops: [
    { code: 'UFM-R', name: 'UFANVELI MALE RETAIL' },
    { code: 'UFM-W', name: 'UFANVELI MALE WHOLESALE' },
    { code: 'UFH-1', name: 'UFANVELI HULHUMALE SHOP (1)' },
    { code: 'UFH-2', name: 'UFANVELI HULHUMALE SHOP (2)' },
    { code: 'UFG', name: 'UFANVELI GALOLHU SHOP' },
    { code: 'UFA', name: 'UFANVELI ATHOLHU SHOP' },
    { code: 'UBS', name: 'UFANVELI BAZARU SHOP (UBS)' },
  ],
  warehouses: [
    {
      code: 'HMCGD',
      name: 'HULHUMALE GODOWN',
      locations: [
        { code: 'HMCGD-DG', name: '01. Dry godown' },
        { code: 'HMCGD-C01', name: '02. Container 01' },
        { code: 'HMCGD-C02', name: '03. Container 02' },
        { code: 'HMCGD-C03', name: '04. Container 03' },
        { code: 'HMCGD-C04', name: '05. Container 04' },
        { code: 'HMCGD-C05', name: '06. Container 05' },
        { code: 'HMCGD-C06', name: '07. Container 06' },
        { code: 'HMCGD-C07', name: '08. Container 07' },
        { code: 'HMCGD-C08', name: '09. Container 08' },
        { code: 'HMCGD-C09', name: '10. Container 09' },
        { code: 'HMCGD-C10', name: '11. Container 10' },
        { code: 'HMCGD-C11', name: '12. Container 11' },
        { code: 'HMCGD-C12', name: '13. Container 12' },
        { code: 'HMCGD-C13', name: '14. Container 13' },
        { code: 'HMCGD-C14', name: '15. Container 14' },
        { code: 'HMCGD-C15', name: '16. Container 15' },
        { code: 'HMCGD-C16', name: '17. Container 16' },
        { code: 'HMCGD-C17', name: '18. Container 17' },
        { code: 'HMCGD-C18', name: '19. Container 18' },
        { code: 'HMCGD-C19', name: '20. Container 19' },
        { code: 'HMCGD-C20', name: '21. Container 20' },
        { code: 'HMCGD-C21', name: '22. Container 21' },
        { code: 'HMCGD-C22', name: '23. Container 22' },
        { code: 'HMCGD-C23', name: '24. Container 23' },
        { code: 'HMCGD-C24', name: '25. Container 24' },
        { code: 'HMCGD-C25', name: '26. Container 25' },
        { code: 'HMCGD-C26', name: '27. Container 26' },
        { code: 'HMCGD-C27', name: '28. Container 27' },
        { code: 'HMCGD-C28', name: '29. Container 28' },
        { code: 'HMCGD-C29', name: '30. Container 29' },
        { code: 'HMCGD-C30', name: '31. Container 30' },
      ],
    },
    {
      code: 'MCG',
      name: "MALE CENTRAL GODOWN",
      locations: [
        { code: 'MCG-GW', name: "01. Male' Godowns & Warehouses" },
        { code: 'MCG-CH', name: "02. Male' Chocolate Godown" },
        { code: 'MCG-SA', name: "03. Male' Salsa Godown" },
        { code: 'MCG-DH', name: "04. Male' Dharavandhoo Godown" },
        { code: 'MCG-KC1', name: "05. Male' Kurahaage Chiller1" },
        { code: 'MCG-KC2', name: "06. Male' Kurahaage Chiller2" },
        { code: 'MCG-DU', name: "07. Male' Dushin Godown" },
        { code: 'MCG-ZE', name: "08. Male' Zeibi Godown" },
        { code: 'MCG-DO', name: "09. Male' Doores Godown" },
        { code: 'MCG-AC1', name: "10. Male' Aroma Chiller1" },
        { code: 'MCG-AC2', name: "11. Male' Aroma Chiller2" },
        { code: 'MCG-DC', name: "12. Male' Doores Chiller" },
        { code: 'MCG-DF', name: "13. Male' Doores Freezer" },
        { code: 'MCG-BC', name: "14. Male' Banana Container" },
        { code: 'MCG-DN', name: "15. Male' Dhannage Go down" },
      ],
    },
  ],
};

// Flat list for dropdowns
export const ALL_LOCATIONS = [
  // Shops
  { value: 'UFM-R', label: 'UFANVELI MALE RETAIL' },
  { value: 'UFM-W', label: 'UFANVELI MALE WHOLESALE' },
  { value: 'UFH-1', label: 'UFANVELI HULHUMALE SHOP (1)' },
  { value: 'UFH-2', label: 'UFANVELI HULHUMALE SHOP (2)' },
  { value: 'UFG', label: 'UFANVELI GALOLHU SHOP' },
  { value: 'UFA', label: 'UFANVELI ATHOLHU SHOP' },
  { value: 'UBS', label: 'UFANVELI BAZARU SHOP (UBS)' },
  // Hulhumale Godown
  { value: 'HMCGD-DG', label: 'HULHUMALE GODOWN - Dry godown' },
  { value: 'HMCGD-C01', label: 'HULHUMALE GODOWN - Container 01' },
  { value: 'HMCGD-C02', label: 'HULHUMALE GODOWN - Container 02' },
  { value: 'HMCGD-C03', label: 'HULHUMALE GODOWN - Container 03' },
  { value: 'HMCGD-C04', label: 'HULHUMALE GODOWN - Container 04' },
  { value: 'HMCGD-C05', label: 'HULHUMALE GODOWN - Container 05' },
  { value: 'HMCGD-C06', label: 'HULHUMALE GODOWN - Container 06' },
  { value: 'HMCGD-C07', label: 'HULHUMALE GODOWN - Container 07' },
  { value: 'HMCGD-C08', label: 'HULHUMALE GODOWN - Container 08' },
  { value: 'HMCGD-C09', label: 'HULHUMALE GODOWN - Container 09' },
  { value: 'HMCGD-C10', label: 'HULHUMALE GODOWN - Container 10' },
  { value: 'HMCGD-C11', label: 'HULHUMALE GODOWN - Container 11' },
  { value: 'HMCGD-C12', label: 'HULHUMALE GODOWN - Container 12' },
  { value: 'HMCGD-C13', label: 'HULHUMALE GODOWN - Container 13' },
  { value: 'HMCGD-C14', label: 'HULHUMALE GODOWN - Container 14' },
  { value: 'HMCGD-C15', label: 'HULHUMALE GODOWN - Container 15' },
  { value: 'HMCGD-C16', label: 'HULHUMALE GODOWN - Container 16' },
  { value: 'HMCGD-C17', label: 'HULHUMALE GODOWN - Container 17' },
  { value: 'HMCGD-C18', label: 'HULHUMALE GODOWN - Container 18' },
  { value: 'HMCGD-C19', label: 'HULHUMALE GODOWN - Container 19' },
  { value: 'HMCGD-C20', label: 'HULHUMALE GODOWN - Container 20' },
  { value: 'HMCGD-C21', label: 'HULHUMALE GODOWN - Container 21' },
  { value: 'HMCGD-C22', label: 'HULHUMALE GODOWN - Container 22' },
  { value: 'HMCGD-C23', label: 'HULHUMALE GODOWN - Container 23' },
  { value: 'HMCGD-C24', label: 'HULHUMALE GODOWN - Container 24' },
  { value: 'HMCGD-C25', label: 'HULHUMALE GODOWN - Container 25' },
  { value: 'HMCGD-C26', label: 'HULHUMALE GODOWN - Container 26' },
  { value: 'HMCGD-C27', label: 'HULHUMALE GODOWN - Container 27' },
  { value: 'HMCGD-C28', label: 'HULHUMALE GODOWN - Container 28' },
  { value: 'HMCGD-C29', label: 'HULHUMALE GODOWN - Container 29' },
  { value: 'HMCGD-C30', label: 'HULHUMALE GODOWN - Container 30' },
  // Male Central Godown
  { value: 'MCG-GW', label: "MALE CENTRAL GODOWN - Male' Godowns & Warehouses" },
  { value: 'MCG-CH', label: "MALE CENTRAL GODOWN - Male' Chocolate Godown" },
  { value: 'MCG-SA', label: "MALE CENTRAL GODOWN - Male' Salsa Godown" },
  { value: 'MCG-DH', label: "MALE CENTRAL GODOWN - Male' Dharavandhoo Godown" },
  { value: 'MCG-KC1', label: "MALE CENTRAL GODOWN - Male' Kurahaage Chiller1" },
  { value: 'MCG-KC2', label: "MALE CENTRAL GODOWN - Male' Kurahaage Chiller2" },
  { value: 'MCG-DU', label: "MALE CENTRAL GODOWN - Male' Dushin Godown" },
  { value: 'MCG-ZE', label: "MALE CENTRAL GODOWN - Male' Zeibi Godown" },
  { value: 'MCG-DO', label: "MALE CENTRAL GODOWN - Male' Doores Godown" },
  { value: 'MCG-AC1', label: "MALE CENTRAL GODOWN - Male' Aroma Chiller1" },
  { value: 'MCG-AC2', label: "MALE CENTRAL GODOWN - Male' Aroma Chiller2" },
  { value: 'MCG-DC', label: "MALE CENTRAL GODOWN - Male' Doores Chiller" },
  { value: 'MCG-DF', label: "MALE CENTRAL GODOWN - Male' Doores Freezer" },
  { value: 'MCG-BC', label: "MALE CENTRAL GODOWN - Male' Banana Container" },
  { value: 'MCG-DN', label: "MALE CENTRAL GODOWN - Male' Dhannage Go down" },
];
